version: '3.1'

services:
    devsecops-bootcamp:
        build:
            context: ./
            dockerfile: ./Dockerfile
            args:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
            - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
        container_name: devsecops-bootcamp
        ports:
            - 5000:5000
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
            - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
        network_mode: bridge
